module.exports = {

    INIT_BALANCE:'INIT_BALANCE',

    BUY_STOCK:"BUY_STOCK",
    BUY_STOCK_SUCCESS:"BUY_STOCK_SUCCESS",
    BUY_STOCK_FAIL:"BUY_STOCK_FAIL",

    SELL_STOCK:"SELL_STOCK",
    SELL_STOCK_SUCCESS:"SELL_STOCK_SUCCESS",
    SELL_STOCK_FAIL:"SELL_STOCK_FAIL",

    PLAYER_TRANSACTION:"PLAYER_TRANSACTION",

    START_TURN:"START_TURN",
    END_TURN:"END_TURN",

    CLEAR:"CLEAR"

};