module.exports = {

    USER_REGISTER:'USER_REGISTER',
    USER_REGISTER_SUCCESS:'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL:'USER_REGISTER_FAIL',

    CREATE_GAME:'CREATE_GAME',
    CREATE_GAME_SUCCESS:'CREATE_GAME_SUCCESS',
    CREATE_GAME_FAIL:'CREATE_GAME_FAIL',

    JOIN_GAME:'JOIN_GAME',
    JOIN_GAME_SUCCESS:'JOIN_GAME_SUCCESS',
    JOIN_GAME_FAIL:'JOIN_GAME_FAIL',

    JOIN_EXISTING_GAME:'JOIN_EXISTING_GAME',
    JOIN_EXISTING_GAME_SUCCESS:'JOIN_EXISTING_GAME_SUCCESS',
    JOIN_EXISTING_GAME_FAIL:'JOIN_EXISTING_GAME_FAIL',

    USER_SUCCESSFULLY_JOINED:"USER_SUCCESSFULLY_JOINED"


};