module.exports = {

    USER_REGISTER:'USER_REGISTER',
    USER_REGISTER_SUCCESS:'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL:'USER_REGISTER_FAIL',

    CREATE_GAME:'CREATE_GAME',
    CREATE_GAME_SUCCESS:'CREATE_GAME_SUCCESS',
    CREATE_GAME_FAIL:'CREATE_GAME_FAIL',

};